import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import * as Popover from "@radix-ui/react-popover";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Templete With redix ui </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <Popover.Root>
          <Popover.Trigger className="PopoverTrigger text-3xl font-bold">
            More info
          </Popover.Trigger>
          <Popover.Portal>
            <Popover.Content className="PopoverContent" sideOffset={5}>
              Some more info…
              <Popover.Arrow className="PopoverArrow" />
            </Popover.Content>
          </Popover.Portal>
        </Popover.Root>
      </main>
    </div>
  );
}
